name: PlatformIO Dependabot
on:
  schedule:
      interval: "weekly"
  workflow_dispatch:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: run PlatformIO Dependabot
    steps:
    - name: PlatformIO Dependabot
      uses: peterus/platformio_dependabot@v1.2.0